import type { ServerState } from './servers.ts';
import { serializeCell } from './engines.ts';

export interface Feature {
  id: string;
  since: 3 | 4 | 5;
  title: string;
  blurb: string;
  /** Statements run (auto-commit) before the demo query. */
  setup?: string[];
  /** The demo query — returns rows shown in the UI. */
  sql: string;
}

/**
 * Firebird features grouped by the version that introduced them. Each demo is a
 * single result-returning statement (with optional setup DDL/DML), so it runs on
 * a fresh connection and shows a row. Verified against FB3/4/5.
 */
export const FEATURES: Feature[] = [
  // ── Firebird 3 ────────────────────────────────────────────────────────────
  {
    id: 'boolean',
    since: 3,
    title: 'BOOLEAN data type',
    blurb: 'A real SQL boolean with TRUE/FALSE/UNKNOWN literals and three-valued logic.',
    sql: `select true as always_true, cast('false' as boolean) as parsed, (1 = 1) as expr from rdb$database`,
  },
  {
    id: 'window',
    since: 3,
    title: 'Window functions',
    blurb: 'ROW_NUMBER / RANK / running aggregates via OVER(...) — analytics without self-joins.',
    sql: `select rdb$relation_id as id,
       row_number() over (order by rdb$relation_id) as rn,
       count(*) over () as total
from rdb$relations where rdb$system_flag = 1 rows 6`,
  },
  {
    id: 'identity',
    since: 3,
    title: 'IDENTITY columns',
    blurb: 'GENERATED BY DEFAULT AS IDENTITY — auto-increment keys without a manual generator+trigger.',
    setup: [
      `recreate table ff_feat_id (id integer generated by default as identity primary key, name varchar(20))`,
      `insert into ff_feat_id (name) values ('alpha')`,
      `insert into ff_feat_id (name) values ('beta')`,
    ],
    sql: `select id, name from ff_feat_id order by id`,
  },

  // ── Firebird 4 ────────────────────────────────────────────────────────────
  {
    id: 'decfloat',
    since: 4,
    title: 'DECFLOAT',
    blurb: 'IEEE-754 decimal floating point (16/34 digits) — exact decimal math, no binary rounding.',
    sql: `select cast(1 as decfloat(34)) / 3 as one_third,
       cast('0.1' as decfloat(34)) + cast('0.2' as decfloat(34)) as exact_sum
from rdb$database`,
  },
  {
    id: 'int128',
    since: 4,
    title: 'INT128 / NUMERIC(38)',
    blurb: '128-bit integers and 38-digit fixed-point numerics.',
    sql: `select cast(170141183460469231731687303715884105727 as int128) as max_int128 from rdb$database`,
  },
  {
    id: 'tztz',
    since: 4,
    title: 'TIME/TIMESTAMP WITH TIME ZONE',
    blurb:
      'Zone-aware temporals with named zones and AT TIME ZONE conversion — one instant, many local faces. ' +
      'The driver returns zoned values as JS Dates (a pure UTC instant, zone metadata dropped); ' +
      'the text columns are rendered server-side to show the zone arithmetic.',
    sql: `select cast(cast('2024-06-15 09:30:00 America/New_York' as timestamp with time zone) as varchar(50)) as in_new_york,
       cast(cast('2024-06-15 09:30:00 America/New_York' as timestamp with time zone) at time zone 'UTC' as varchar(50)) as in_utc,
       cast(cast('2024-06-15 09:30:00 America/New_York' as timestamp with time zone) at time zone 'Europe/Paris' as varchar(50)) as in_paris,
       cast('2024-06-15 09:30:00 America/New_York' as timestamp with time zone) as as_js_date
from rdb$database`,
  },
  {
    id: 'crypthash',
    since: 4,
    title: 'CRYPT_HASH / built-in crypto',
    blurb: 'SHA-256/512 hashing, ENCRYPT/DECRYPT and RSA functions built into SQL.',
    sql: `select crypt_hash('fast-firebird' using sha256) as sha256 from rdb$database`,
  },

  // ── Firebird 5 ────────────────────────────────────────────────────────────
  {
    id: 'multi-returning',
    since: 5,
    title: 'Multi-row RETURNING',
    blurb: 'INSERT/UPDATE/DELETE ... RETURNING can now return every affected row, not just one.',
    setup: [`recreate table ff_feat_ret (id integer primary key, dbl integer)`],
    sql: `insert into ff_feat_ret
select rdb$relation_id, rdb$relation_id * 2 from rdb$relations where rdb$system_flag = 1 rows 4
returning id, dbl`,
  },
  {
    id: 'skip-locked',
    since: 5,
    title: 'SKIP LOCKED',
    blurb: 'Grab the next unlocked rows for queue-style workloads without blocking on locked ones.',
    setup: [
      `recreate table ff_feat_q (id integer primary key, status varchar(10))`,
      `insert into ff_feat_q values (1, 'ready')`,
      `insert into ff_feat_q values (2, 'ready')`,
      `insert into ff_feat_q values (3, 'ready')`,
    ],
    sql: `select id, status from ff_feat_q order by id rows 2 for update with lock skip locked`,
  },
  {
    id: 'merge-returning',
    since: 5,
    title: 'MERGE ... RETURNING',
    blurb: 'Upsert with WHEN [NOT] MATCHED and a RETURNING clause in one statement.',
    setup: [
      `recreate table ff_feat_m (id integer primary key, v varchar(10))`,
      `insert into ff_feat_m values (1, 'old')`,
    ],
    sql: `merge into ff_feat_m t
using (select 1 as id, 'new' as v from rdb$database union all select 2, 'insert' from rdb$database) s
on t.id = s.id
when matched then update set v = s.v
when not matched then insert (id, v) values (s.id, s.v)
returning t.id, t.v`,
  },
];

export function featuresFor(version: number | undefined) {
  return FEATURES.map((f) => ({
    id: f.id,
    since: f.since,
    title: f.title,
    blurb: f.blurb,
    setup: f.setup ?? [],
    sql: f.sql,
    available: version != null && version >= f.since,
  }));
}

/** Run a feature demo (setup auto-commit, then the demo query) on a fresh pool connection. */
export async function tryFeature(state: ServerState, setup: string[], sql: string) {
  const t0 = performance.now();
  try {
    const rows = await state.pool.use(async (att) => {
      for (const s of setup) await att.execute(s);
      return att.query(sql);
    });
    const serialized = rows.map((r) => {
      const o: Record<string, unknown> = {};
      for (const [k, v] of Object.entries(r as Record<string, unknown>)) o[k] = serializeCell(v);
      return o;
    });
    return { rows: serialized, rowCount: serialized.length, ms: +(performance.now() - t0).toFixed(2) };
  } catch (err) {
    return { rows: [], rowCount: 0, ms: +(performance.now() - t0).toFixed(2), error: (err as Error).message.split('\n').slice(0, 3).join(' ') };
  }
}
