import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { defineConfig } from 'vitepress';

// Generated by `pnpm api` (TypeDoc) — absent until the first API build.
let typedocSidebar: unknown[] = [];
try {
  typedocSidebar = JSON.parse(
    readFileSync(fileURLToPath(new URL('../api/typedoc-sidebar.json', import.meta.url)), 'utf8'),
  );
} catch {
  // `vitepress dev` without a prior `pnpm api` — API section just renders empty.
}

// Deployed at https://mreis1.github.io/fast-firebird/ (GitHub Pages).
export default defineConfig({
  title: 'fast-firebird',
  description:
    'The pure-TypeScript Firebird driver for Node.js that treats round trips as the scarcest resource — and proves it against real servers.',
  base: '/fast-firebird/',
  lang: 'en-US',
  lastUpdated: true,
  head: [
    ['link', { rel: 'icon', href: '/fast-firebird/favicon.ico' }],
    ['meta', { property: 'og:title', content: 'fast-firebird — Firebird driver for Node.js' }],
    [
      'meta',
      {
        property: 'og:description',
        content: 'Pure-TypeScript Firebird wire-protocol driver: FB 3/4/5/6, pooling, blobs, batch, Drizzle ORM.',
      },
    ],
  ],
  themeConfig: {
    logo: '/mark.svg',
    search: { provider: 'local' },
    nav: [
      { text: 'Guide', link: '/guide/getting-started', activeMatch: '/guide/' },
      { text: 'Benchmarks', link: '/guide/performance' },
      { text: 'API', link: '/api/', activeMatch: '/api/' },
      {
        text: 'npm',
        items: [
          { text: '@fast-firebird/core', link: 'https://www.npmjs.com/package/@fast-firebird/core' },
          { text: '@fast-firebird/drizzle', link: 'https://www.npmjs.com/package/@fast-firebird/drizzle' },
        ],
      },
    ],
    sidebar: {
      '/guide/': [
        {
          text: 'Introduction',
          items: [
            { text: 'Why fast-firebird?', link: '/guide/why' },
            { text: 'Getting started', link: '/guide/getting-started' },
            { text: 'Migrating from node-firebird', link: '/guide/migrate-from-node-firebird' },
          ],
        },
        {
          text: 'Core guide',
          items: [
            { text: 'Queries & parameters', link: '/guide/queries' },
            { text: 'Transactions', link: '/guide/transactions' },
            { text: 'Bulk writes (executeBatch)', link: '/guide/batch' },
            { text: 'Streaming result sets', link: '/guide/streaming' },
            { text: 'Blobs', link: '/guide/blobs' },
            { text: 'Data types', link: '/guide/types' },
            { text: 'Prepared statements & cache', link: '/guide/prepared-statements' },
            { text: 'Connection pooling', link: '/guide/pooling' },
          ],
        },
        {
          text: 'Beyond queries',
          items: [
            { text: 'Multi-statement scripts', link: '/guide/scripts' },
            { text: 'Events (POST_EVENT)', link: '/guide/events' },
            { text: 'Services API', link: '/guide/services' },
            { text: 'Legacy CHARSET NONE', link: '/guide/charset-none' },
            { text: 'Firebird 6', link: '/guide/firebird6' },
            { text: 'Auth, encryption & compression', link: '/guide/security' },
          ],
        },
        {
          text: 'Ecosystem',
          items: [
            { text: 'Drizzle ORM', link: '/guide/drizzle' },
            { text: 'Performance', link: '/guide/performance' },
          ],
        },
      ],
      '/api/': [
        {
          text: 'API Reference',
          items: typedocSidebar,
        },
      ],
    },
    socialLinks: [{ icon: 'github', link: 'https://github.com/mreis1/fast-firebird' }],
    footer: {
      message: 'MIT Licensed. Contains data derived from the Firebird project under IDPL/IPL.',
      copyright: 'Copyright © 2026 Marcio Reis',
    },
    outline: { level: [2, 3] },
    editLink: {
      pattern: 'https://github.com/mreis1/fast-firebird/edit/main/docs/:path',
      text: 'Edit this page on GitHub',
    },
  },
  ignoreDeadLinks: [
    // TypeDoc cross-links into source files that are not part of the site.
    /^https?:\/\/localhost/,
  ],
});
